### ISSUE TITLE
Pulse things with space in name lose connectivity

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/pulse-adapter#12] opened 2019-11-14 14:52 UTC
WebThings Gateway 0.10

STR:
* Install pulse adapter
* Configure adapter
* Add configuration with a space in the name field
* Save
* Add a pulse thing with a space in the name
* Navigate to pulse thing page & reload

Expected:
* Pulse works as expected

Actual:
* Pulse thing is dimmed

Error message in WebSocket:
`
{"messageType":"error","data":{"code":400,"status":"400 Bad Request","message":"Thing pulse-bar%20baz not found","request":{"id":"pulse-bar%20baz","messageType":"addEventSubscription","data":{"turnedOn":{},"turnedOff":{}}}}}`

**Comment by mrstegeman** [comment] 2019-11-14 16:09
This is somewhat of a duplicate of #6, but the space behavior is new.

**Closed** 2019-11-14 16:35 UTC
Labels: bug
